name: Setup test environment
description: Install test dependencies
inputs:
  needs_codecov:
    description: Whether to download the codecov uploader
    default: false
runs:
  using: composite
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install tox
        python3 --version
        if [[ ${{ inputs.needs_codecov }} =~ [Yy]es|[Tt]rue ]]; then
          mkdir -p "$HOME/.local/bin/"
          curl --silent --show-error --output "${PATH%%:*}/codecov" https://ansible-ci-files.s3.us-east-1.amazonaws.com/codecov/linux/codecov
          chmod +x "${PATH%%:*}/codecov"
          echo "Codecov $(codecov --version)"
        fi
