name: Setup test environment
description: Install test dependencies
inputs:
  needs_codecov:
    description: Whether to download the codecov uploader
    default: false
runs:
  using: composite
  steps:
    - name: Install Python dependencies
      shell: bash
      run: |
        pip install --upgrade pip
        pip install tox
        python --version
        echo $PATH

    - name: Fetch Codecov uploader
      if: inputs.needs_codecov
      shell: bash
      runs: |
        curl --silent --show-error --remote-name https://ansible-ci-files.s3.us-east-1.amazonaws.com/codecov/linux/codecov
        chmod +x codecov
        ./codecov --version
