name: CI
on:
  push:
    branches:
      - devel

  pull_request:
    branches:
      - devel


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: quay.io/ansible/ansible-runner-test-container:1.0.0
      env:
        PIP_CACHE_DIR: ${{ runner.temp }}/.cache/pip
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run linters
        run: tox -e linters


  docs:
    name: Docs
    runs-on: ubuntu-latest
    container:
      image: quay.io/ansible/ansible-runner-test-container:1.0.0
      env:
        PIP_CACHE_DIR: ${{ runner.temp }}/.cache/pip

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build docs
        run: tox -e docs


  tests:
    name: ${{ matrix.test_type.name }} - ${{ matrix.env.name }}
    runs-on: ubuntu-latest
    container:
      image: quay.io/ansible/ansible-runner-test-container:1.0.0
      env:
        PIP_CACHE_DIR: ${{ runner.temp }}/.cache/pip

    strategy:
      fail-fast: false
      matrix:
        test_type:
          - name: Unit
            path: test/unit

          - name: Integration
            path: test/integration

        env:
          - name: ansible-base
            tox_env: ansible-base

          - name: 3.8
            tox_env: py38

          - name: 3.9
            tox_env: py39

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tests
        run: tox -e ${{ matrix.env.tox_env }} ${{ matrix.test_type.path }}

      - name: Upload coverage data
        continue-on-error: true
        run: codecov --file test/coverage/coverage.xml --name ${{ matrix.test_type.name }}-${{ matrix.env.name }}
