name: CI
on:
  push:
    branches:
      - devel

  pull_request:
    branches:
      - devel


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: quay.io/ansible/fedora34-test-container:2.1.0
      env:
        PIP_CACHE_DIR: $RUNNER_TEMP/.cache/pip
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install test dependencies
        uses: ./.github/actions/setup

      - run: |
          env
          whoami
          ls -Al $HOME
          ls -Al /github

      - name: Run linters
        run: tox -e linters


  docs:
    name: Docs
    runs-on: ubuntu-latest
    container:
      image: quay.io/ansible/fedora34-test-container:2.1.0
      env:
        PIP_CACHE_DIR: $RUNNER_TEMP/.cache/pip

    steps:
      - uses: actions/checkout@v2

      - name: Install test dependencies
        uses: ./.github/actions/setup

      - name: Build docs
        run: tox -e docs


  tests:
    name: ${{ matrix.test_type.name }} - ${{ matrix.env.name }}
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.env.image }}
      env:
        PIP_CACHE_DIR: $RUNNER_TEMP/.cache/pip

    strategy:
      fail-fast: false
      matrix:
        test_type:
          - name: Unit
            path: test/unit

          - name: Integration
            path: test/integration

        env:
          - name: ansible-base
            tox_env: ansible-base
            image: quay.io/ansible/fedora32-test-container:2.1.0

          - name: 3.8
            tox_env: py38
            image: quay.io/ansible/fedora32-test-container:2.1.0

          - name: 3.9
            tox_env: py39
            image: quay.io/ansible/fedora34-test-container:2.1.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install test dependencies
        uses: ./.github/actions/setup
        with:
          needs_codecov: yes

      - name: Tests
        run: |
          tox -e ${{ matrix.env.tox_env }} ${{ matrix.test_type.path }}

      - name: Upload coverage data
        run: codecov --file test/coverage/coverage.xml
