name: CI
on:
  push:
    branches:
      - devel

  pull_request:
    branches:
      - devel


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: quay.io/ansible/fedora34-test-container:2.1.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install test dependencies
        uses: ./.github/actions/setup

      - run: |
          env
          whoami
          ls -Al $HOME
          ls -Al /github

      - name: Run linters
        run: tox -e linters


  docs:
    name: Docs
    runs-on: ubuntu-latest
    container: quay.io/ansible/fedora34-test-container:2.1.0

    steps:
      - uses: actions/checkout@v2

      - name: Install test dependencies
        uses: ./.github/actions/setup

      - name: Build docs
        run: tox -e docs


  unit:
    name: Unit - ${{ matrix.env.name }}
    runs-on: ubuntu-latest
    container: ${{ matrix.env.image }}

    strategy:
      fail-fast: false
      matrix:
        env:
          - name: Fedora Py3.9
            tox_env: py39
            image: quay.io/ansible/fedora34-test-container:2.1.0

          - name: RHEL Py3.8
            tox_env: py38
            image: registry.access.redhat.com/ubi8/python-38

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install test dependencies
        uses: ./.github/actions/setup
        with:
          needs_codecov: yes

      - name: Tests
        run: |
          tox -e ${{ matrix.env.tox_env }} test/unit/

      - name: Upload coverage data
        run: codecov --file test/coverage/coverage.xml


  integration:
    name: Integration
    runs-on: ubuntu-latest
    container: ${{ matrix.env.image }}

    strategy:
      fail-fast: false
      matrix:
        env:
          - tox_env: py39
            image: quay.io/ansible/fedora34-test-container:2.1.0

          - tox_env: py38
            image: registry.access.redhat.com/ubi8/python-38


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install test dependencies
        uses: ./.github/actions/setup
        with:
          needs_codecov: yes

      - name: Tests
        run: |
          tox -e ${{ matrix.env.tox_env }} test/integration/

      - name: Upload coverage data
        run: codecov --file test/coverage/coverage.xml
