name: CI
on:
  push:
    branches:
      - devel

  pull_request:
    branches:
      - devel


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    container: quay.io/ansible/default-test-container:3.8.0
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install test dependencies
        uses: ./.github/actions/setup

      - name: Run linters
        run: tox -e linters

  docs:
    name: Docs
    runs-on: ubuntu-latest
    container: quay.io/ansible/default-test-container:3.8.0
    steps:
      - uses: actions/checkout@v2

      - name: Install test dependencies
        uses: ./.github/actions/setup

      - name: Build docs
        run: tox -e docs

  unit:
    name: Unit
    runs-on: ubuntu-latest
    container: quay.io/ansible/default-test-container:3.8.0

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - ver: 3.8
            env: py38

          - ver: 3.9
            env: py38

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install test dependencies
        uses: ./.github/actions/setup
        with:
          needs_codecov: yes
          python_version: ${{ matrix.python_version.ver }}

      - name: Tests
        run: |
          tox -e ${{ matrix.python_version.env }} test/unit/

      - name: Upload coverage data
        run: codecov --file test/coverage/coverage.xml


  integration:
    name: Integration
    runs-on: ubuntu-latest
    container: quay.io/ansible/default-test-container:3.8.0

    strategy:
      fail-fast: false
      matrix:
        python_version:
          - ver: 3.8
            env: py38

          - ver: 3.9
            env: py38

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install test dependencies
        uses: ./.github/actions/setup
        with:
          needs_codecov: yes
          python_version: ${{ matrix.python_version.ver }}

      - name: Tests
        run: |
          tox -e ${{ matrix.python_version.env }} test/integration/

      - name: Upload coverage data
        run: codecov --file test/coverage/coverage.xml
