name: CI
on:
  push:
    branches:
      - devel

  pull_request:
    branches:
      - devel


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup

      - run: tox -e linters

  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.8
          - 3.9
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: ./.github/actions/setup
        with:
          needs_codecov: yes

      - name: Docs
        run: |
          tox -e docs

      - name: Units
        run: |
          tox -e py

      - name: Upload coverage
        run: |
          tox -e report,codecov
